spring.application.name=directorio-consulta

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/directorio_db
spring.datasource.username=postgres
spring.datasource.password=2002
spring.jpa.hibernate.ddl-auto=update
telegram.bot.username=oficio_consulta_bot
telegram.bot.token=8410288408:AAGPa8TQWmfqMi_c0t_KauIg8uvrlFujChg
#spring.profiles.active=local
